//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kurs.cpp
//  @ Date : 17.05.2024
//  @ Author : 
//
//


#include <iostream>
#include "Kurs.h"

Kurs::Kurs(string nazwa, Wydzial* wydzial) {
    this->nazwa = nazwa;
    this->wydzial = wydzial;

}

void Kurs::dodajNauczyciel(Nauczyciel * nauczyciel) {
    this->nauczyciele.push_back(nauczyciel);
}

void Kurs::dodajMaterialy(string tytul, string zawartosc) {
    this->materialy.insert(pair<string, string>(tytul, zawartosc));
    cout << "Dodano material" << endl;
}

void Kurs::dodajStudenta(Student* student) {

    for(auto &i: this->studenci) {
        if(i->getLogin() == student->getLogin()) {
            cout << "Student jest juz zapisany na kurs" << endl;
            return;
        }
    }
    cout << "Zapisano na kurs studenta " + student->getNazwisko() << endl;
    this->studenci.push_back(student);
}

void Kurs::wyswietlMaterialy() {

    if (materialy.size() == 0) {
        cout << "Brak materialow na kursie " + this->nazwa << endl;
        return;
    }

    for(auto &i: this->materialy) {
        cout << "Tytul: " << i.first << " Tresc: " << i.second << endl;
    }
}

void Kurs::usunMaterial(string tytul) {
    this->materialy.erase(tytul);
}

void Kurs::ocenStudentow() {
    for(auto &i: this->studenci) {
        int ocena;
        cout << "Podaj ocene dla studenta " + i->getNazwisko() << endl;
        cin >> ocena;
        oceny[i] = ocena;
    }
}

void Kurs::setNazwa(string nazwa) {
    this->nazwa = nazwa;
}

string Kurs::getNazwa() {
    return this->nazwa;

}

vector<Nauczyciel *> Kurs::getNauczyciele() {
    return nauczyciele;
}

vector<Student *> Kurs::getStudenci() {
    return studenci;
}

void Kurs::wyswietlOcenyStudentow() {
    cout << "Oceny studentow:" << endl;

    for (auto &i: this->oceny) {
        cout << i.first->getIndeks() << " " << i.first->getNazwisko() << " " << i.first->getImie() << i.second << endl;
    }

};
void Kurs::wyswietlOcene(Student* student){
    cout << "Twoja ocena: " << this->oceny[student] << endl;
};



