//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Nauczyciel.cpp
//  @ Date : 17.05.2024
//  @ Author : 
//
//


#include "Nauczyciel.h"

Nauczyciel::Nauczyciel(string imie, string nazwisko, string login, string haslo)
        : Uzytkownik(imie, nazwisko, login, haslo) {

}

void Nauczyciel::dodajKurs(Kurs *kurs) {

}

void Nauczyciel::usunKurs(Kurs *kurs) {

}

void Nauczyciel::dodajWydzial(Wydzial *wydzial) {

}

void Nauczyciel::usunWydzial(Wydzial *wydzial) {

}

