//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Nauczyciel.h
//  @ Date : 17.05.2024
//  @ Author : 
//
//


#if !defined(_NAUCZYCIEL_H)
#define _NAUCZYCIEL_H

#include "Uzytkownik.h"
#include "Wydzial.h"
#include "Nauczyciel.h"
#include "Student.h"
#include "System.h"
#include "Kurs.h"


using namespace std;
class Uzytkownik;
class Wydzial;
class Nauczyciel;
class Student;
class Kurs;
class System;

class Nauczyciel : public Uzytkownik {
public:
	Nauczyciel(string imie, string nazwisko, string login, string haslo);
	void dodajKurs(Kurs* kurs);
	void usunKurs(Kurs* kurs);
	void dodajWydzial(Wydzial* wydzial);
	void usunWydzial(Wydzial* wydzial);

    vector<Wydzial *> getWydzialy();
    vector<Kurs *> getProwadzoneKursy();

private:
	vector<Kurs*> prowadzoneKursy;
	vector<Wydzial*> wydzialy;
};

#endif  //_NAUCZYCIEL_H
