//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.cpp
//  @ Date : 17.05.2024
//  @ Author : 
//
//


#include "Student.h"

Student::Student(string imie, string nazwisko, string login, string haslo)
: Uzytkownik(imie, nazwisko, login, haslo)
{

}

void Student::dodajKurs(Kurs* kurs) {

}

void Student::wyjdzZKursu(Kurs* kurs) {

}

void Student::wyswietlKursy() {

}

int Student::getIndeks() {
    return 0;

}

void Student::setIndeks(int indeks) {

}

