//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uzytkownik.h
//  @ Date : 17.05.2024
//  @ Author : 
//
//


#if !defined(_UZYTKOWNIK_H)
#define _UZYTKOWNIK_H

#include <string>
#include <vector>
#include <map>


using namespace std;

class Wydzial;

class Kurs;
class System;


class Uzytkownik {
public:

	Uzytkownik(string imie, string nazwisko, string login, string haslo);
	Uzytkownik(string login, string haslo);
	string getImie();
	string getNazwisko();
	string getLogin();
	string getHaslo();
	bool sprawdzHaslo(string haslo);
	void setImie(string imie);
	void setNazwisko(string nazwisko);
	void setLogin(string login);
	void setHaslo(string haslo);
	void wyswietlUzytkownika();
private:
	string imie;
	string nazwisko;
	string login;
	string haslo;
};

#endif  //_UZYTKOWNIK_H
