//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wydzial.h
//  @ Date : 17.05.2024
//  @ Author : 
//
//


#if !defined(_WYDZIAL_H)
#define _WYDZIAL_H
#include <string>
#include <vector>
#include <map>
#include "Uzytkownik.h"
#include "Wydzial.h"
#include "Nauczyciel.h"
#include "Student.h"
#include "System.h"
#include "Kurs.h"

using namespace std;
class Uzytkownik;
class Wydzial;
class Nauczyciel;
class Student;
class Kurs;
class System;


class Wydzial {
public:
	Wydzial(string nazwa);
	string getNazwa();
	void dodajNauczyciela(Nauczyciel* nauczyciel);
	void wyswietlNauczycieli();
	void usunNauczyciela(Nauczyciel* nauczyciel);
	void dodajKurs(Kurs* kurs);
	void wyswietlKursy();
	void usunKurs(Kurs* kurs);
    vector<Nauczyciel*> getNauczyciele();
    vector<Kurs*> getKursy();

private:
	string nazwa;
	vector<Nauczyciel*> nauczyciele;
	vector<Kurs*> kursy;
};

#endif  //_WYDZIAL_H
